@startuml
'https://plantuml.com/component-diagram
top to bottom direction


"Aged Brie" --> [updateQuality]
Backstage --> [updateQuality]
Sulfuras --> [updateQuality]
Common --> [updateQuality]

[updateQuality] <-- [legacyCode]

@enduml